[main]
shell=nu --config repos/collectionScripts/nushell/config.nu --env-config repos/collectionScripts/nushell/env.nu
dpi-aware=yes
font=Cascadia Code NF
initial-window-mode=maximized

[cursor]
style=beam
unfocused-style=hollow
blink=yes

# OneDark
# Based on kitty theme
[colors]
alpha=0.9
cursor=ABB2BF cccccc
foreground=ABB2BF
background=282C34
regular0=3F4451   # black
regular1=E06C75   # red
regular2=98C379   # green
regular3=D19A66   # yellow
regular4=61AFEF   # blue
regular5=C678DD   # purple
regular6=56B6C2   # cyan
regular7=D7DAE0   # white
bright0=4F5666    # bright black
bright1=BE5046    # bright red
bright2=A5E075    # bright green
bright3=E5C07B    # bright yellow
bright4=4DC4FF    # bright blue
bright5=DE73FF    # bright purple
bright6=4CD1E0    # bright cyan
bright7=E6E6E6    # bright white
selection-foreground=282C34
selection-background=ABB2BF
