language = en
font-family=Cascadia Code NF
maximize = true
auto-update = off
link-url = true

#########
## Clipboard
#########
clipboard-read = allow
clipboard-write = allow
clipboard-trim-trailing-spaces = true
copy-on-select = clipboard

#########
## Cursor
#########
cursor-style = block
cursor-style-blink = true
cursor-click-to-move = true
mouse-hide-while-typing = true

#########
## Color scheme
#########

background-opacity = 0.9
foreground = #ABB2BF
background = #282C34

selection-foreground = #282C34
selection-background = #ABB2BF

cursor-color = #ABB2BF
cursor-text = #282C34
# black
palette = 0=#3F4451
palette = 8=#4F5666

# red
palette = 1=#E06C75
palette = 9=#BE5046

# green
palette = 2=#98C379
palette = 10=#A5E075

# yellow
palette = 3=#D19A66
palette = 11=#E5C07B

# blue
palette = 4=#61AFEF
palette = 12=#4DC4FF

# purple
palette = 5=#C678DD
palette = 13=#DE73FF

# cyan
palette = 6=#56B6C2
palette = 14=#4CD1E0

# white
palette = 7=#D7DAE0
palette = 15=#E6E6E6

