[data_store.sqlite]
db_url = "/var/lib/rustical/db.sqlite3"

[dav_push]
enabled = true

[frontend]
allow_password_login = true
enabled = true

[http]
bind = "0.0.0.0:58443"

[nextcloud_login]
enabled = false

[tracing]
opentelemetry = false
