- name: Install geolite2 updater script
  vars:
    is_become: false
    user: root
    dest_folder: "."
  become: "{{is_become}}"
  block:
    - name: "Create '{{dest_folder}}' directory"
      ansible.builtin.file:
        path: "{{dest_folder}}"
        state: directory
        owner: "{{user}}"
        group: "{{user}}"
    - name: "Download maxmind-updater AS {{ [ dest_folder, 'maxmind-db-updater.py'] | path_join}}"
      become: true
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/DoumanAsh/maxmind-db/refs/heads/master/updater/maxmind-db-updater.py"
        dest: "{{ [ dest_folder, 'maxmind-db-updater.py'] | path_join}}"
        force: false
        owner: "{{user}}"
        group: "{{user}}"
        mode: u=rwx,g=rx,o=rx
    - name: "Execute {{ [ dest_folder, 'maxmind-db-updater.py'] | path_join}}"
      become: true
      ansible.builtin.command:
        cmd: "{{ [ dest_folder, 'maxmind-db-updater.py'] | path_join}} --country"
        creates: "{{ [ dest_folder, 'GeoLite2-Country.mmdb'] | path_join}}"
